import { createClient } from "@/utils/supabase/server";
import LevelTestClient from "./LevelTestClient";

export const metadata = {
  title: "Free English Level Assessment | Study with Asma",
  description: "Take our free 15-minute English level assessment to find out your current proficiency and get course recommendations.",
};

export default async function LevelTestPage() {
  const supabase = await createClient();

  // Fetch the latest level test generated by the admin
  const { data: test, error } = await supabase
    .from("tests")
    .select("*")
    .eq("content_type", "level_test")
    .order("created_at", { ascending: false })
    .limit(1)
    .single();

  if (error || !test) {
    return (
      <div className="min-h-[70vh] flex flex-col items-center justify-center text-center px-4">
        <h1 className="text-3xl font-extrabold text-foreground mb-4">English Level Assessment</h1>
        <p className="text-muted-foreground max-w-md mx-auto">
          We are currently updating our level assessment test. Please check back later or contact us to schedule a manual assessment.
        </p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-muted/30 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-10">
          <h1 className="text-3xl sm:text-4xl font-extrabold text-foreground mb-4">
            Free English Level Assessment
          </h1>
          <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
            Find out your current English proficiency level in just 15 minutes. This helps us recommend the perfect course for your IELTS goals.
          </p>
        </div>

        <LevelTestClient testData={test.content_data} />
      </div>
    </div>
  );
}
